import 'package:retcore/src/config/imports.dart';

const tBlack = Colors.black;
const tWhite = Colors.white;
const tGrey = Colors.grey;
const tFocusedColor = Colors.blueAccent;
const tRed = Colors.red;
const tGreen = Colors.green;
const tRedAccent = Colors.redAccent;
const tOrange = Colors.deepOrangeAccent;
Color tSnackBarSuccessColor = RetCoreColor(colorCode: '1E4634');
Color tSnackBarErrorColor = RetCoreColor(colorCode: '801336');
Color tSnackBarAlertColor = RetCoreColor(colorCode: 'FB8C20');
Color tSnackBarInfoColor = RetCoreColor(colorCode: '276690');
Color tSnackBarSuccessContainerColor = RetCoreColor(colorCode: '2D6A4F');
Color tSnackBarErrorContainerColor = RetCoreColor(colorCode: 'C72C41');
Color tSnackBarAlertContainerColor = RetCoreColor(colorCode: 'FCA652');
Color tSnackBarInfoContainerColor = RetCoreColor(colorCode: '3282B8');
Color tDialogSuccessContainerColor = RetCoreColor(colorCode: '12C069');
Color tDialogErrorContainerColor = RetCoreColor(colorCode: '91011E');
Color tDialogAlertContainerColor = RetCoreColor(colorCode: '29363F');
Color tDialogInfoContainerColor = RetCoreColor(colorCode: 'C99207');
Color tDialogConfirmButtonColor = RetCoreColor(colorCode: '4CB050');
Color tDialogConfirmContainerColor = RetCoreColor(colorCode: '1CAFA2');
